---
title: "mergeKO.Rmd"
author: "Joy-El Talbot"
date: "2022-02-22"
output: 
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{R, code=readLines("mergeKo.R"), echo=TRUE, eval=TRUE}
Now use the `knit` command within your RStudio window to knit this Rmd file to html. You may view a preview of the mergeKO.html within RStudio or open it with any web browser.

## DESeq2 and tximport

Now write an R script with the contents shown below to import the Salmon alignments into `DESeq2` and perform differential expression analysis. As with the previous script, since I provide the complete script, look up each of the functions used and make sure you understand how they are used here.

```r
#!/usr/bin/env Rscript
# de.R
library(tximport)
library(readr)
library(DESeq2)

# TODO: update constants for your machine
# Define constants
TESTING <- TRUE # Change to FALSE if using entire Samples set
RESULTS_DIR <- "/home/j.talbot/binf2/BINF6309-Spring2022-Talbot-ClassDemos/Module4Refactor/results"
AIPTASIA_DIR <- "/work/courses/BINF6309/AiptasiaMiSeq"

# for testing purposes - alternative samples table
testing_samples <- data.frame(Sample = c("Aip02", "Aip02", "Aip02", "Aip02"),
                              Menthol = c("Control", "Control", "Menthol", "Menthol"),
                              Vibrio = c("Control", "Vibrio", "Control", "Vibrio"))
head(testing_samples)

# True script begins
tx2gene <- read.csv(file.path(RESULTS_DIR, "tx2gene.csv"))
head(tx2gene)

if (TESTING) {
  print("***Running test with Aip02 only***")
  samples <- testing_samples
} else {
  samples <- read.csv(file.path(AIPTASIA_DIR, "Samples.csv"), header=TRUE)
}
head(samples)


files <- file.path(RESULTS_DIR, "quant", samples$Sample, "quant.sf")
txi <- tximport(files, type="salmon", tx2gene=tx2gene)

dds <- DESeqDataSetFromTximport(txi, colData = samples, 
                                design = ~ Menthol + Vibrio)

dds$Vibrio <- relevel(dds$Vibrio, ref = "Control")
dds$Menthol <- relevel(dds$Menthol, ref = "Control")
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]
dds <- DESeq(dds)

padj <- .05
minLog2FoldChange <- .5
dfAll <- data.frame()
# Get all DE results except Intercept, and "flatten" into a single file.
for (result in resultsNames(dds)){
  if(result != 'Intercept'){
    res <- results(dds, alpha=.05, name=result)
    dfRes <- as.data.frame(res)
    dfRes <- subset(subset(dfRes, select=c(log2FoldChange, padj)))
    dfRes$Factor <- result
    dfAll <- rbind(dfAll, dfRes)
  }
}
head(dfAll)

write.csv(dfAll, file=file.path(RESULTS_DIR, "dfAll.csv"))
# end of de.R script
